<?php

namespace app\modules\catalog\models\form;


use app\modules\catalog\models\entity\Product;

class ProductFromSibagoForm extends Product
{
    public $lazyImageUrl;

    public static function tableName()
    {
        return Product::tableName(); // TODO: Change the autogenerated stub
    }
}