version: "3.9"
services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3361:3306"
  fpm:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    links:
      - db
    volumes:
      - ./:/var/www/kotofey.store
  nginx:
    links:
      - fpm
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "27015:80"
    volumes:
      - ./:/var/www/kotofey.store