<?

namespace app\models\search;

use app\models\entity\Category;
use app\models\entity\Product;
use yii\base\Model;
use yii\data\ActiveDataProvider;

class CategorySearchForm extends Category
{
    public static function tableName()
    {
        return "category";
//        return parent::tableName(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['id'], 'integer'],
            [['name'], 'string'],
        ];
    }

    public function scenarios()
    {
        return Model::scenarios();
    }
}