<?

namespace app\widgets\order_custom_product;


use app\widgets\notification\Notify;
use app\widgets\order_custom_product\models\OrderCustomProductForm;
use yii\base\Widget;

class OrderCustomProduct extends Widget
{
    public function run()
    {
        $model = new OrderCustomProductForm();

        if (\Yii::$app->request->isPost) {

            if ($model->load(\Yii::$app->request->post())) {

                if ($model->validate()) {

                    if ($model->save()) {

                        Notify::setSuccessNotify("Ваш заказ отправлен. Наши менеджеры свяжутся с вами в ближайшее время");
                        \Yii::$app->controller->refresh();

                    }

                }

            }

        }

        return $this->render("default", ['model' => $model]);
    }

    public
    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}