<?php

namespace app\modules\catalog\controllers;

use app\modules\catalog\models\entity\CompositionProducts;
use app\modules\catalog\models\entity\CompositionType;
use app\modules\catalog\models\entity\NotifyAdmission;
use app\modules\catalog\models\entity\Properties;
use app\modules\catalog\models\entity\PropertiesProductValues;
use app\modules\catalog\models\helpers\OfferHelper;
use app\modules\site\models\tools\Debug;
use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\Controller;
use app\modules\site\models\tools\System;
use app\modules\seo\models\tools\Attributes;
use app\modules\seo\models\tools\og\OpenGraph;
use app\modules\seo\models\tools\og\OpenGraphProduct;
use app\modules\catalog\models\entity\ProductCategory;
use app\modules\catalog\models\entity\Offers;
use yii\web\Response;

class ProductController extends Controller
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionView($id)
    {
        $offer = Offers::findBySlug($id);
        if (!$offer instanceof Offers) throw new \yii\web\NotFoundHttpException("Товар не найден.");

        $category = ProductCategory::findOne($offer->category_id);

        if (!empty($offer->seo_description)) {
            Attributes::metaDescription($offer->seo_description);
        } else {
            if (!empty($offer->description)) {
                Attributes::metaDescription($offer->description);
            } else {
                Attributes::metaDescription(sprintf('В нашем интернет-магазине зоотоваров в продаже  имеется %s по низкой цене в Барнауле. За каждую покупку выполучите 5%% бонусов, а мы доставим бесплатно!', $offer->name));
            }
        }

        if (!empty($offer->seo_keywords)) {
            Attributes::metaKeywords($offer->seo_keywords);
        } else {
            Attributes::metaKeywords(explode(';', sprintf("купить %s в барнауле;интернет-зоомагазин;зоомагазин интернет барнаул;анго зоомагазин интернет барнаул;интернет зоомагазин с доставкой", $offer->name)));
        }

        Attributes::canonical(System::protocol() . "://" . System::domain() . "/product/" . $offer->slug . "/");

        OpenGraphProduct::title($offer->name);
        if (!empty($offer->description)) {
            OpenGraph::description($offer->description);
            Attributes::metaDescription($offer->description);
        }
        OpenGraphProduct::type();
        OpenGraphProduct::url(System::protocol() . "://" . System::domain() . "/" . Yii::$app->controller->action->id . "/" . $offer->slug . "/");
        OpenGraphProduct::amount($offer->price);
        OpenGraphProduct::currency('RUB');

        if ($offer->media) OpenGraphProduct::image(OfferHelper::getImageUrl($offer, true));

        $propertiesValues = PropertiesProductValues::find()
            ->where(['product_id' => $offer->id])
            ->andWhere(['not in', 'property_id', ArrayHelper::getColumn(Properties::find()->select('id')->where(['is_show_site' => false])->all(), 'id')])
            ->all();
        OfferHelper::addVisitedItem($offer->id);

        $compositionGroup = [];
        $compositions = CompositionProducts::find()->where(['product_id' => $offer->id])->all();
        foreach ($compositions as $composit_value_item) {
            $compositionGroup[$composit_value_item->composition->composition_type_id]['group'] = CompositionType::findOne($composit_value_item->composition->composition_type_id);
            $compositionGroup[$composit_value_item->composition->composition_type_id]['items'][] = $composit_value_item;
        }

        return $this->render('view', [
            'offer' => $offer,
            'category' => $category,
            'compositionGroup' => $compositionGroup,
            'propertiesValues' => $propertiesValues,
        ]);
    }


    public function actionSaveNotifyAdmission()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model = new NotifyAdmission();

        if ($model->load(Yii::$app->request->post())) {
            if ($model->validate() && $model->save()) {
                return Json::encode([
                    'success' => 1,
                ]);
            } else {
                return Json::encode([
                    'false' => 1,
                    'message' => $model->getErrors()
                ]);
            }
        }
    }


    public function actionRemoveNotifyAdmission()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $data = Yii::$app->request->post();

        if (NotifyAdmission::findOne(['email' => $data['email'], 'product_id' => $data['product_id']])->delete()) return Json::encode([
            'success' => 1,
        ]);
    }
}