<?php

namespace app\modules\order\controllers;


use yii\rest\Controller;

class OrderRepeatRestController extends Controller
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionCreate()
    {
    }

    public function actionIndex()
    {
    }

    public function actionDelete()
    {
    }
}