<?php

namespace app\widgets\search;

use app\models\entity\Search;
use yii\base\Widget;

class SearchWidget extends Widget
{
    public $view = 'default';

    public function run()
    {
        $model = new Search();
        return $this->render($this->view, [
            'model' => $model,
        ]);
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}