<?php


namespace app\modules\site\widgets\HelpDesk;


use yii\base\Widget;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

class HelpDeskWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        ob_start();
        ob_implicit_flush(false);
    }

    public function run()
    {
        $content = ob_get_clean();
        $html = Html::beginTag('div', ['class' => 'accordion help-panel-container', 'id' => 'help-panel-accordion']);
        $html .= Html::beginTag('div', ['class' => 'help-panel-list']);

        $html .= $content;

        $html .= Html::endTag('div');
        $html .= Html::endTag('div');
        return $html;
    }

    public static function addItem($title,$text="")
    {
        $uniq = uniqid();
        $outHtml = "";

        $outHtml .= Html::beginTag('div', ['class' => 'help-panel-list__item']);
            $outHtml .= Html::beginTag('div', ['class' => 'help-panel-list-header', 'id' => 'heading' . $uniq]);
                $outHtml .= Html::beginTag('a', ['class' => 'collapsed', 'data-toggle' => 'collapse', 'data-target' => '#collapse' . $uniq, 'aria-expanded' => 'false', 'aria-controls' => '#collapse' . $uniq]);
                    $outHtml .= Html::tag('span', Html::tag('i', false, ['class' => 'fas fa-paw']), ['class' => 'help-panel-list__ico']);
                    $outHtml .= Html::tag('span', $title);
                $outHtml .= Html::endTag('a');
            $outHtml .= Html::endTag('div');

            $outHtml .= Html::beginTag('div', ['class' => "collapse", 'id' => 'collapse' . $uniq, 'aria-labelledby' => 'heading' . $uniq, 'data-parent' => "#help-panel-accordion"]);
                $outHtml .= Html::tag('div', $text, ['class' => 'help-panel-list-body']);
            $outHtml .= Html::endTag('div');
        $outHtml .= Html::endTag('div');

        return $outHtml;
    }
}