<?php


namespace app\modules\site\widgets\HelpDesk;


use yii\base\Widget;
use yii\helpers\Html;

class HelpDeskWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub


        $content = ob_get_clean();
        $html = Html::beginTag('div', ['class' => 'accordion help-panel-container', 'id' => 'help-panel-accordion']);
        $html .= Html::beginTag('div', ['class' => 'help-panel-list']);

        $html .= $content;

        $html .= Html::endTag('div');
        $html .= Html::endTag('div');
        return $html;
    }
}