<?php

namespace app\modules\feed;

use app\modules\site\MainModule;
use yii\helpers\Url;

class Module extends MainModule
{
    public $controllerNamespace = 'app\modules\feed\controllers';
    public $name = 'Поисковой контент';

    public function init()
    {
        parent::init();
    }

    public function getName()
    {
        return parent::getName(); // TODO: Change the autogenerated stub
    }

    public function menuIndex()
    {
        return [
            ['name' => 'Поисковой контент', 'url' => Url::to(['/admin/feed/feed-backend/index'])],
        ];
    }
}
