<?php

namespace app\widgets\inspector;


use app\models\entity\User;
use yii\base\Widget;
use app\widgets\inspector\InspectorAssets;

class InspectorWidget extends Widget
{
	public $template = 'default';

	public function init()
	{
		InspectorAssets::register($this->getView());
		parent::init(); // TODO: Change the autogenerated stub
	}

	public function run()
	{
		if (!User::isRole('Developer')) {
			return false;
		}

//		return $this->render($this->template);
	}
}